apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 5s

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: drone_telemetry
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      version: Flux
      organization: drone-project
      defaultBucket: drone_telemetry
      tlsSkipVerify: true
    editable: true
